### ISSUE TITLE
Reasons of nonfunctionality (HFINF4) chart for HeRAMS NGA Project (id:10) is not working

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#181] opened 2019-08-19 16:44 UTC
Reasons of nonfunctionality (HFINF4) chart for HeRAMS NGA is not working under functionality section (id: 23; sort number: 2). I tried to use "transpose" and "not transpose", but the chart does not work under these conditions. I also tried using a different code (HFFUNCT): the chart is working but not on using HFINF4 code again.

<img width="1680" alt="Screen Shot 2019-08-20 at 12 42 18 AM" src="https://user-images.githubusercontent.com/50957748/63283294-6c309a00-c2e3-11e9-873e-a25e22b04863.png">

**Comment by SamMousa** [comment] 2019-08-21 09:30
Duplicate of #184

**Closed by SamMousa** 2019-08-21 09:30 UTC
