### ISSUE TITLE
Reasons of non-accessibility (HFACC2) chart for HeRAMS NGA Project (id:10) is not working

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#183] opened 2019-08-19 17:19 UTC
Reasons of non-accessibility (HFACC2) chart for HeRAMS NGA is also not working under Accessibility section (id:27 , sort: 2) is also not working

<img width="1680" alt="Screen Shot 2019-08-20 at 1 18 25 AM" src="https://user-images.githubusercontent.com/50957748/63285520-7bfead00-c2e8-11e9-950c-3f89030d7053.png">

**Comment by SamMousa** [comment] 2019-08-21 09:29
Duplicate of #184

**Closed by SamMousa** 2019-08-21 09:29 UTC
Labels: test on staging
