### ISSUE TITLE
Data export / Limit the export to "last" record only

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#347] opened 2020-02-24 13:27 UTC
Would need to have the option to limit the export to the "last=true" values only (i.e. the last version of each HF/UOID)

Hope that can be met quite rapidly as hopefully light and in high demand from Yemen

**Comment by SamMousa** [comment] 2020-02-24 13:57
We don't know whether a record is the last one, so this is a bit more involved. The date should be part of the export so the workaround is to just filter out the data in excel or your analytics tool.

> Hope that can be met quite rapidly as hopefully light and in high demand from Yemen

Let's not make everything urgent. Yemen has been running for months, then this is added 20 minutes ago and it is immediately urgent.

**Comment by SamuelPetragallo** [comment] 2020-02-24 14:03
Urgent taking into account it shouldn't be difficult that is.

The last record is defined by the "UOID" and "Update" fields (in case of several records with same UOID/Update fields (user mistake) with the response id)

**Comment by SamMousa** [comment] 2020-02-24 14:10
Let's discuss this tomorrow during the meeting: #348.
The issue is that I do not know what you mean by `quite rapidly`. 

Furthermore this change as proposed would limit data export, so might affect permissions as well (should it be possible to limit certain users / roles to only download current and not history data?). These things need to be considered.

The next release has not yet been planned; but regardless of when it is, this can definitely be included.

**Comment by SamMousa** [comment] 2020-02-25 10:08
Filter by date (reuse filtering from dashboard)

**Comment by luna404** [comment] 2020-02-26 15:05
This will need some more testing, but here's an initial feedback. 

1. By default, users should still be able to export all data. Only if they choose to limit the data should they be able to enter a date.
2. Rather than keeping the field blank, the default date should always be today.
3. There seems to be an issue with the filter (both in the dashboard and the export). The filter should always export the latest record that is equal to or before the selected date. In the example below, I set three dates: `26-jan-2020`, `01-jan-2019` and `01-jan-2015`. The export is correct for today's date, but not for the others. For the second date it should export the second record with date of update 06-11-2018. For 2015 it should not export any record as no data was entered before 01-jan-2015.

![image](https://user-images.githubusercontent.com/18245059/75355948-8c06d300-58af-11ea-8ee2-d2a46245aa76.png)

4. Minor issue, but the calendar overlaps with the help text. This is not crucial for this release but would be nice if it could be resolved in the future.

**Comment by SamMousa** [comment] 2020-02-26 15:10
> By default, users should still be able to export all data. Only if they choose to limit the data should they be able to enter a date.

Leaving it blank does that, as is explained by the text below the field.

> Rather than keeping the field blank, the default date should always be today.

This would break 1.

> There seems to be an issue with the filter (both in the dashboard and the export). The filter should always export the latest record that is equal to or before the selected date. In the example below, I set three dates: 26-jan-2020, 01-jan-2019 and 01-jan-2015. The export is correct for today's date, but not for the others. For the second date it should export the second record with date of update 06-11-2018. For 2015 it should not export any record as no data was entered before 01-jan-2015.

Create a new bug report if you've found an issue with the filter. Also provide the dataset you used for testing, specifically the workspace or project ID.

> Minor issue, but the calendar overlaps with the help text. This is not crucial for this release but would be nice if it could be resolved in the future.

This is expected, this is essentially how a dropdown list works and any other widget that expands when activated. We are not in control of the date picker, each device / browser decides how / where to render it.

**Comment by SamMousa** [comment] 2020-02-26 15:49
@SamuelPetragallo I vaguely remember that we originally decided not to filter away HFs (ie if there is only 1 entry we wanted it included no matter the date filter).

I have now changes this to work as @luna404 requested, so if you set a date that is before the date of collection the HF will not show at all.

**Comment by SamMousa** [comment] 2020-02-26 16:01
@luna404 can you confirm that it works as expected (also double check the dashboard)?

Then we can mark this issue as resolved.
If we need to redesign the UI we can do that in a new issue / iteration. --> Here we also might want to offer other kinds of filters.

**Comment by luna404** [comment] 2020-02-27 13:18
I confirm it's working (both dashboard and export), but I'm a little reluctant implementing it before the user interface is more intuitive. Could we at least make the help text more explicit? I don't think users will understand that if they don't enter a date it will export all records.

Proposed label: `Enter a date to limit the export to the last record before or equal to the selected date for each health facility. To export all historic records of a health facility, leave the field blank. `

Also, I noticed there are a lot of deleted records still in the database. Is this just an issue on staging or will we have the same issue on prod?

**Comment by SamMousa** [comment] 2020-02-27 13:20
We will have the same issue; I can do a full remove & resync after the release. (Will do it on staging as soon as all testing is complete)

**Comment by JeffDotingco** [comment] 2020-02-27 13:51
This is working @SamMousa in staging. I exported a workspace for HeRAMS NGA -- Yobe / Damaturu with 108 records wherein 38 records have "true" labels in the Last column. The downloaded data with 2/27/2020 report date option is also 38 records. No duplicate records upon checking the UOID / Subject ID in the exported data.

**Comment by SamMousa** [comment] 2020-02-27 13:55
@luna404 I have updated the hint, okay for a first release?

**Comment by luna404** [comment] 2020-02-28 09:58
Thanks for updating the hint.

I keep having issues trying to download project level data with a date filter. Try exporting the data for Nigeria (https://herams-staging.org/project/30/export). I have no issue exporting it without a filter, but every time i set a date filter, it results in a time out error. I have done it several times now and keep getting the same result.

**Comment by SamMousa** [comment] 2020-02-28 10:16
This has been fixed now, please confirm that you still get the correct data.
I've fully rewritten the query that does the filtering meaning there is a risk it is not returning the correct data..

@JeffDotingco please confirm as well!

**Comment by JeffDotingco** [comment] 2020-02-28 10:24
For workspace Yobe / Damaturu (28 "true" records and 108 entries), I exported a total of 39 records filtered on report date 2-28-2020, 1 HF with 2 records were imported (UOID:  rRlrgR)

**Comment by SamMousa** [comment] 2020-02-28 11:48
So that means it does not work?

**Comment by SamMousa** [comment] 2020-02-28 11:50
I'm getting 38 rows, can you retry @JeffDotingco ?

**Comment by JeffDotingco** [comment] 2020-02-28 11:59
38 rows as well for Yobe / Damaturu @SamMousa

**Comment by SamMousa** [comment] 2020-02-28 12:04
So we're good for release then?

**Comment by luna404** [comment] 2020-02-28 12:17
Yes, we are.

**Comment by JeffDotingco** [comment] 2020-02-28 13:35
I exported workspace Yobe / Damaturu in PROD @SamMousa, but now I only have 36 rows. This is 38 rows in STAGING (exported downloaded another dataset just now)

**Comment by SamMousa** [comment] 2020-02-28 15:00
What about PROD?

**Comment by JeffDotingco** [comment] 2020-02-28 15:07
Already 38 rows in PROD @SamMousa for Yobe / Damaturu.

**Closed** 2020-02-28 15:15 UTC
Labels: env:prod, env:staging, flow:released, urgency:normal
